services:
  web:    
    build: .
    volumes:
      - app_data:/app
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:17
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bookstore_dev_db
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  app_data:
