services:
  web:    
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=bookstore_db

volumes:
  postgres_data:
