# Generated by Django 5.2.5 on 2025-09-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="product.category"),
        ),
    ]
