name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: [3.13]
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        

    - name: Install dependencies
      run: poetry install

    - name: Run migrations
      run: poetry run python manage.py migrate

    - name: Criar arquivo .env no CI
      run: |
        echo "DEBUG=1" >> .env
        echo "SECRET_KEY=foo" >> .env
        echo "DJANGO_ALLOWED_HOST=localhost 127.0.0.1[::1]" >> .env
        echo "SQL_ENGINE=django.db.backends.postgresql" >> .env
        echo "SQL_DATABASE=bookstore_dev_db" >> .env
        echo "SQL_USER=bookstore_dev" >> .env
        echo "SQL_PASSWORD=bookstore_dev" >> .env
        echo "SQL_HOST=db" >> .env
        echo "SQL_PORT=5432" >> .env

    - name: Run test
      run: poetry run python manage.py test