name: Python Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'poetry'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Check versions
      run: |
        python --version
        poetry --version

    - name: Install dependencies with Poetry
      run: poetry install --no-root

    - name: Run tests
      run: poetry run python manage.py test